import styles from './consulting.module.css';

const services = [
  ['Applications & Business Automation','Dynamics, Power Platform, application development, workflows, and practical automation designed around the way people actually work.','Dynamics 365 · Power Platform · C#/.NET'],
  ['Data Integration & ETL','Reliable data movement across databases, applications, APIs, files, ERP systems, and reporting platforms—with validation built in.','SSIS/ETL · APIs · Data Quality'],
  ['Dynamics & Business Systems','Practical support and delivery across Dynamics 365, Dynamics GP, Dataverse, Customer Insights, and connected applications.','Dynamics 365 · Dynamics GP · Dataverse'],
  ['Power Platform Solutions','Purposeful Power Apps and Power Automate solutions that simplify work, reduce manual effort, and connect teams to trustworthy data.','Power Apps · Power Automate · Connectors'],
  ['Application & Production Support','Thorough investigation of business-critical incidents across applications, databases, integrations, and operational workflows.','Root Cause Analysis · IIS · Jira'],
  ['Technical Leadership & Documentation','Requirements, solution design, vendor coordination, workflow diagrams, runbooks, and knowledge transfer that make solutions sustainable.','Leadership · SDLC · Miro'],
];

const capabilities = [
  ['SQL, Data & Reporting',['SQL Server','T-SQL','Stored Procedures','SSIS / ETL','Data Warehousing','Data Migration','Data Validation','Performance Tuning','Redgate']],
  ['Dynamics & Business Systems',['Dynamics 365 CE','Dynamics GP','Dataverse','Customer Insights - Journeys','Power Apps','Power Automate','SmartConnect','Financial Systems']],
  ['Development & Integration',['C# / .NET','REST APIs','Web Services','JSON / XML','Azure Logic Apps','Azure Functions','Custom Connectors','PowerShell','Git / GitHub']],
  ['Delivery, Support & Leadership',['Requirements Gathering','Solution Design','Technical Leadership','Production Support','Root-Cause Analysis','Agile / SDLC','Jira','Vendor Collaboration','Documentation']],
];

export const metadata = {
  title: 'Gerlich Consulting | Applications, Data, Automation & Integrations',
  description: 'Technology consulting for business applications, Dynamics, Power Platform, data integration, SQL Server, automation, and business-critical systems.',
};

export default function Consulting(){return <main className={styles.page}>
  <nav className={`${styles.wrap} ${styles.nav}`}><a className={styles.brand} href="/consulting"><span>G</span><b>Gerlich Consulting</b></a><div className={styles.navlinks}><a href="#services">Services</a><a href="#capabilities">Capabilities</a><a href="/">Tina's Portfolio</a><a className={styles.navcta} href="#contact">Let's talk</a></div></nav>
  <section className={`${styles.wrap} ${styles.hero}`}><div><p className={styles.eyebrow}>Applications · Data · Automation · Integrations</p><h1>Technology that works <em>as one system.</em></h1><p className={styles.lead}>Gerlich Consulting helps organizations connect and improve business applications, CRM and ERP platforms, automation, integrations, databases, reporting, and the processes behind them.</p><div className={styles.actions}><a className={styles.primary} href="#contact">Start a conversation</a><a className={styles.secondary} href="#services">Explore services</a></div></div><aside className={styles.signal}><span>APPS</span><span>DATA</span><span>SYSTEMS</span></aside></section>
  <section className={`${styles.wrap} ${styles.intro}`}><p className={styles.eyebrow}>What we solve</p><p>When data, applications, and business processes stop working together, the problem rarely lives in just one place. We follow the entire path—and build a solution that holds up beyond launch day.</p></section>
  <section className={`${styles.wrap} ${styles.section}`} id="services"><header className={styles.sectionHead}><div><p className={styles.eyebrow}>Consulting services</p><h2>Technical depth.<br/>Business context.</h2></div><p>Senior-level consulting for organizations that need someone who can move confidently between the stakeholder conversation and the technical details.</p></header><div className={styles.serviceGrid}>{services.map((s,i)=><article key={s[0]}><span className={styles.num}>0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p><small>{s[2]}</small></article>)}</div></section>
  <section className={styles.dark}><div className={styles.wrap}><header className={styles.sectionHead}><div><p className={styles.eyebrow}>Relevant experience</p><h2>Complex work,<br/>made understandable.</h2></div><p>Grounded in real production environments, interconnected systems, and the operational consequences of technology decisions.</p></header><div className={styles.work}><article><span>01</span><div><b>Production systems</b><h3>Connecting manufacturing workflows from source to label</h3><p>Troubleshooting operational systems, ERP and SQL data, production interfaces, and label-printing processes end to end.</p></div></article><article><span>02</span><div><b>Financial data</b><h3>Making ERP data reliable and useful</h3><p>Supporting Dynamics GP-connected financial workflows, reporting, integrations, and data validation.</p></div></article><article><span>03</span><div><b>Business automation</b><h3>Turning requirements into working processes</h3><p>Translating stakeholder needs into Dynamics, Power Platform, database, API, and workflow solutions.</p></div></article></div></div></section>
  <section className={`${styles.wrap} ${styles.section}`} id="capabilities"><header className={styles.sectionHead}><div><p className={styles.eyebrow}>Technical capabilities</p><h2>A broad toolkit,<br/>used with purpose.</h2></div><p>Technology choices follow the business problem—not the other way around.</p></header><div className={styles.capabilityGrid}>{capabilities.map((g,i)=><article key={g[0]}><span className={styles.num}>0{i+1}</span><h3>{g[0]}</h3><div>{g[1].map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section>
  <section className={`${styles.wrap} ${styles.about}`}><div><p className={styles.eyebrow}>About the principal</p><h2>Curious by nature.<br/>Thorough by practice.</h2></div><div><p>Gerlich Consulting is led by Tina Gerlich, a senior technology professional with a Bachelor of Science in Computer Science and deep experience across business applications, Dynamics, Power Platform, integrations, SQL Server, financial systems, and production support.</p><p>Tina's strength is systems thinking: understanding what enters a process, how information moves, where it changes, and what the business ultimately needs.</p><a href="/">Explore Tina's full portfolio →</a></div></section>
  <section className={`${styles.wrap} ${styles.contact}`} id="contact"><div><p className={styles.eyebrow}>Start a conversation</p><h2>Let's make the complicated part clearer.</h2><p>Tell us what is not working, what needs to change, or what you are trying to build.</p></div><div className={styles.contactCard}><b>Email</b><a href="mailto:tgerlich99@gmail.com">tgerlich99@gmail.com</a><b>Phone</b><a href="tel:+15157821086">(515) 782-1086</a><b>Based in</b><span>Chapel Hill, Tennessee · Serving clients remotely</span><a className={styles.primary} href="mailto:tgerlich99@gmail.com?subject=Consulting%20Inquiry">Discuss your project</a></div></section>
  <footer className={`${styles.wrap} ${styles.footer}`}><div className={styles.brand}><span>G</span><b>Gerlich Consulting, LLC</b></div><p>Applications · Data · Automation · Integrations</p><p>© {new Date().getFullYear()} Gerlich Consulting, LLC</p></footer>
  </main>}
